#!/bin/bash

KDB=$(setxkbmap -query | grep layout | awk '{print $2}')

set_keyboard(){
	if [ $KDB == "us" ]
	then
		setxkbmap cz\(qwerty\)
	else
		setxkbmap us
	fi
}

set_keyboard
#	notify-send -u low -i mouse "KBD layout changed";

#pkill -RTMIN+2 i3blocks

setxkbmap -query | grep layout | awk '{print $2}'
